### PR TITLE
fix display of panels that use the bufferedcanvas (again)

### PR DESCRIPTION
**Pull request by holgero**
Re-applying my commit b232bb89898da0acff2b97bd460b801cbace1019
It has been undone by c17bc11169522d6d38436f84fd08baa79e914480
As the later commit had the title 'Slic3r integrated for
Ubuntu 64bit', I don't think this was by intention. Therefore
I redo my change. (Without it pronterface on my PC does not
display the temperature graph, the xy- and z- buttons.)

### CODE REVIEW

**Comment by CtrlC-Root** [comment]
:+1:

**Comment by RRP-support** [comment]
This is an automated reply to your message "Re: [Software] fix display of panels that use the bufferedcanvas
 (again) (#11)" sent to support@reprappro.com.

Dear Alexandru Barbur <notifications@github.com>

Thank you for your email. We endeavour to answer all emails within 24 hours. It may take longer during busy times, and holiday periods. We process all customer queries on a first come first served basis, during our office hours which are 9am to 5pm GMT Mon-Fri.

Other support channels are available. Please refer to the relevant troubleshooting guide for your machine:

Ormerod 2: https://reprappro.com/documentation/ormerod-2/troubleshooting/
Ormerod: https://reprappro.com/documentation/ormerod/troubleshooting/

Huxley Duo: https://reprappro.com/documentation/huxley-duo/troubleshooting/
Huxley: https://reprappro.com/documentation/huxley/troubleshooting/

Mono and Tricolour Mendel: https://reprappro.com/documentation/mendel-tricolour/troubleshooting/

Support is also available from other owners of RepRapPro and other 3D printers, either through the RepRap Forums: https://forums.reprap.org or through IRC which can be accessed from here: https://reprappro.com/support-channel/ (works on Chrome, not Firefox).

Best regards,

RepRapPro Support Team.

**Comment by RRP-support** [comment]
This is an automated reply to your message "Re: [Software] fix display of panels that use the bufferedcanvas
 (again) (#11)" sent to support@reprappro.com.

Dear reprappro <notifications@github.com>

Thank you for your email. We endeavour to answer all emails within 24 hours. It may take longer during busy times, and holiday periods. We process all customer queries on a first come first served basis, during our office hours which are 9am to 5pm GMT Mon-Fri.

Other support channels are available. Please refer to the relevant troubleshooting guide for your machine:

Ormerod 2: https://reprappro.com/documentation/ormerod-2/troubleshooting/
Ormerod: https://reprappro.com/documentation/ormerod/troubleshooting/

Huxley Duo: https://reprappro.com/documentation/huxley-duo/troubleshooting/
Huxley: https://reprappro.com/documentation/huxley/troubleshooting/

Mono and Tricolour Mendel: https://reprappro.com/documentation/mendel-tricolour/troubleshooting/

Support is also available from other owners of RepRapPro and other 3D printers, either through the RepRap Forums: https://forums.reprap.org or through IRC which can be accessed from here: https://reprappro.com/support-channel/ (works on Chrome, not Firefox).

Best regards,

RepRapPro Support Team.

**Comment by RRP-support** [comment]
Hi holgero

Thanks! And sorry for taking so long to include this, for some reason we didn't notice the pull request. We use Ubuntu in-house, and the jog dial and graph had disappeared, but we hadn't got around to fixing it... we tend to connect to our Duet-based printers via ethernet.
And thanks for reminding us of this pull request, CtrlC-Root!

Ian
RepRapPro tech support

**Pull request merged**
